#!/bin/bash
##############################################################################
#
# workspace
# -------------------
# Copy Eclipse workspaces with global settings intact.
#
# @author Abel Luck <abel@guardianproject.info>
# @author Tomas Kramar <kramar.ttomas@gmail.com>
# @date 20 April 2014
# @version 0.2.1
#-----------------------------------------------------------------------------
# Changelog:
# v0.2.1: rename update to copy and remove deploy command
# v0.2.0: renamed to 'workspace' and add update command
##############################################################################
# This code is free, you may do whatever you want with it.
#
function usage ()
{
    echo "$0 <command>"
    echo "-------------------------------------------------------------------"
    echo "Copy Eclipse workspaces with global settings intact."
    echo "------------------------------------------------------------------"
    echo "<command>        copy"
    echo;
    echo "$0 copy <from-workspace> <to-workspace>"
    echo "                 Copy the settings from an existing workspace to"
    echo "                 another workspace. Projects and project settings"
    echo "                 remain untouched."
    exit 1
}

function die {
    echo $1
    exit 1
}
function check_write() {
    if [[ ! ( ( -d "$1" ) && ( -w "$1" ) ) ]]; then
        die "$1 is not a writable directory"
    fi
}

function check_read() {
    if [[ ! ( ( -d "$1" ) && ( -r "$1" ) ) ]]; then
        die "$1 is not a readable directory"
    fi
}

## @param $1: from-wp
## @param $2: to-wp
# assumes perm checks
function copy_settings() {
    from=$1
    to=$2
    mkdir -p "$to/.metadata/.plugins/org.eclipse.core.runtime/" || die "could not create $to"
    cp -R "$from/.metadata/.plugins/org.eclipse.core.runtime/.settings/" "$to/.metadata/.plugins/org.eclipse.core.runtime/" ||
        die "could not copy settings"
}

## @param $1: from-wp
## @param $2: to-wp
function copy() {
    from=$1
    to=$2
    check_read $from
    check_write $to
    copy_settings $from $to
    echo "workspace copied: $to, run eclipse -data $to"
}

if [[ "$#" != "3" ]] ; then
    usage
fi

CMD=$1

case $CMD in
    copy ) copy $2 $3;;
    * ) usage;;
esac


